site_name: gallifrey Documentation
site_url: https://ChrisBoettner.github.io/gallifrey/
repo_url: https://github.com/ChrisBoettner/gallifrey
edit_uri: edit/main/docs/
docs_dir: docs

nav:
  - Home: index.md
  - quickstart.ipynb
  - Tutorials:
      - Stellar Variability: stellar_variability.ipynb
      - Transit: transit.ipynb
      - Comparison: comparison_with_simple_kernel.ipynb
      - Transmission Spectrum: transmission_spectrum.ipynb
      
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: lime
      toggle:
        icon: material/weather-night
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - navigation.sections # Enable section navigation
    - navigation.top # Back-to-top button
    - search.suggest # Improve search with suggestions
    - search.highlight # Highlight search terms
    - content.tabs.link # Allow linking to content tabs
    - content.code.copy # Add copy to clipboard button for code blocks
    - content.code.annotate # Enable code annotation (requires extensions)
    #- toc.integrate # Integrate table of contents
    - header.autohide # Auto-hide header on scroll

extra:
  generator: true # Show "Generated by MkDocs" in the footer (optional)

markdown_extensions:
  #- admonitions # Enable admonition blocks (notes, warnings, etc.)
  - pymdownx.details # Enable <details> and <summary> HTML tags for collapsible sections
  - pymdownx.superfences # Improve code block handling and syntax highlighting
  - pymdownx.inlinehilite # Enable inline code highlighting
  - pymdownx.snippets # Include code snippets from other files
  - pymdownx.emoji: # Enable emojis
  - pymdownx.tabbed: # Enable tabbed content
      alternate_style: true # Optional: Use alternate tab style
  - pymdownx.critic # Enable critic markup for collaborative editing (optional)
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist: # Enable task lists (checkboxes in lists)
      custom_checkbox: true
  # - toc: # Table of contents configuration
  #     permalink: true # Add permalinks to headings
  #     slugify: mkdocs.utils.slugify # Use MkDocs slugify for consistent URLs


plugins:
  - search
  # - literate-nav: 
  #     nav_file_name: SUMMARY.md # File to look for for navigation structure in directories (optional)
  - mkdocstrings: 
      handlers:
          python:
              paths:
                  - .
                  - gallifrey
              options:
                  docstring_style: numpy
  - mkdocs-autoapi:
      autoapi_dir: gallifrey
  - mkdocs-jupyter:
      include_source: True
